#!/usr/bin/python3
# SPDX-License-Identifier: GPLv3

""" print all the words of length letters in probabalistic order """

# pylint: disable=deprecated-module
# pylint: disable=invalid-name
# pylint: disable=no-self-use
# pylint: disable=too-many-branches
# pylint: disable=too-many-locals
# pylint: disable=too-many-statements

import re

from optparse import OptionParser

class Probabilities:
    """ a probability table """
    def __init__(self):
        self.probs = {}

    def add(self, word):
        """ add a word to the dictionary """
        raise NotImplementedError

    def score(self, word):
        """ score a word against the table """
        raise NotImplementedError

class LetterProbabilities(Probabilities):
    """ non-positional letter probabilities """
    def __init__(self):
        Probabilities.__init__(self)

    def add(self, word):
        for letter in word:
            self.probs.setdefault(letter, 0)
            self.probs[letter] += 1

    def score(self, word):
        score = 0
        for letter in word:
            self.probs.setdefault(letter, 0)
            score += self.probs[letter]
        skews = {
            'D':1,  # because verbs
            'S':2,  # because verbs and plurals
        }
        for k, v in skews.items():
            if word[-1] == k:
                score += v
        return score

class PositionalLetterProbabilities(Probabilities):
    """ non-positional letter probabilities """
    def __init__(self):
        Probabilities.__init__(self)

    def add(self, word):
        for pos, letter in enumerate(word):
            self.probs.setdefault(pos, {})
            self.probs[pos].setdefault(letter, 0)
            self.probs[pos][letter] += 1

    def score(self, word):
        score = 0
        for pos, letter in enumerate(word):
            self.probs.setdefault(pos, {})
            self.probs[pos].setdefault(letter, 0)
            score += self.probs[pos][letter]
        skews = {
            'D':1,  # because verbs
            'S':2,  # because verbs and plurals
        }
        for k, v in skews.items():
            if word[-1] == k:
                score += v
        return score

class Word:
    """ Our word class """

    def __init__(self, word, probs):
        self.probs = probs
        self.word = word

    def _score(self, probs=None):
        """ score a word against the probability table """
        if probs is None:
            probs = self.probs
        return probs.score(self.word)

    @property
    def score(self):
        """ score a word against our probability table """

        return self._score()

    def __cmp__(self, other):
        """ compare two words given the probability table """

        scorea = self.score
        scoreb = other.score

        if scorea > scoreb:
            return 1
        if scorea < scoreb:
            return -1
        return 0

    def __lt__(self, other):
        """ compare two words given the probability table """

        scorea = self.score
        scoreb = other.score

        return scorea < scoreb

    def __str__(self):
        return self.word

    def __repr__(self):
        return self.word

def parse_command_line():
    """ parse the command line """
    usage = "usage: %prog [-b BADEXP] [-g GOODEXP] [-p present] [-a absent] [-d|-D] [-l LENGTH]"
    parser = OptionParser(usage=usage)
    parser.add_option("-b", "--bad", help="Bad expression", action="append",
                      dest="badexps", default=[], metavar="REGEX")
    parser.add_option("-g", "--good", help="Good expression", action="append",
                      dest="goodexps", default=[], metavar="REGEX")
    parser.add_option("-p", "--present", help="present characters",
                      action="append", dest="present", default=[])
    parser.add_option("-a", "--absent", help="absent characters",
                      action="append", dest="absent", default=[])
    parser.add_option("-l", "--length", help="Word length", action="store",
                      dest="length", default=5)
    parser.add_option("-d", "--allow-duplicates", help="allow duplicate letters",
                      action="store_true", dest="duplicates", default=None)
    parser.add_option("-D", "--no-duplicates", help="don't allow duplicate letters",
                      action="store_false", dest="duplicates")
    parser.add_option("-s", "--show-score", help="show the word score",
                      action="store_true", dest="show_score", default=False)
    parser.add_option("-P", "--positional", help="use positional probability table",
                      action="store_true", dest="positional", default=False)

    options, args = parser.parse_args()

    return options, args

def main():
    """ our main loop """

    options, args = parse_command_line()
    if args:
        raise ValueError

    badexps = [re.compile(exp) for exp in options.badexps]
    goodexps = [re.compile(exp) for exp in options.goodexps]

    words = []
    if options.positional:
        probs = PositionalLetterProbabilities()
    else:
        probs = LetterProbabilities()

    if options.duplicates is None:
        if badexps or goodexps or options.present or options.absent:
            options.duplicates = True
        else:
            options.duplicates = False

    with open("sowpods.txt") as wordfile:
        wordlist = wordfile.readlines()
        for word in wordlist:
            word = word.strip()

            if len(word) != options.length:
                continue

            probs.add(word)
            found = False
            lettermap = {}
            for letter in word:
                lettermap.setdefault(letter, 0)
                lettermap[letter] += 1
                if lettermap[letter] > 1:
                    found = True

            if found and not options.duplicates:
                continue

            found = False
            for exp in badexps:
                if exp.match(word) is not None:
                    found = True
                    break
            if found:
                continue

            present = {}
            for opt in options.present:
                for letter in opt:
                    present[letter] = 0
            absent = {}
            for opt in options.absent:
                for letter in opt:
                    absent[letter] = 0

            found = False
            for letter in word:
                if letter in absent.keys():
                    found = True
                try:
                    del present[letter]
                except KeyError:
                    pass
            if len(present.keys()) != 0:
                continue
            if found:
                continue

            if goodexps:
                for exp in goodexps:
                    if exp.match(word):
                        words.append(Word(word, probs))
            else:
                words.append(Word(word, probs))

    #print("probs:%s" % (probs,))

    words.sort()
    for word in words:
        if options.show_score:
            print("%s %s" % (word,word.score))
        else:
            print("%s" % (word,))

if __name__ == '__main__':
    main()
